global using NUnit.Framework;
global using OpenQA.Selenium;
global using OpenQA.Selenium.Chrome;
global using OpenQA.Selenium.Edge;
global using OpenQA.Selenium.Firefox;
global using OpenQA.Selenium.Support.UI;
global using System;
global using System.Collections.Generic;
global using System.Linq;
global using static ecommerceFinalProject.Utils.StaticHelpers;
global using ecommerceFinalProject.POMClasses;
global using TechTalk.SpecFlow;