global using NUnit.Framework;
global using OpenQA.Selenium;
global using OpenQA.Selenium.Support;
global using OpenQA.Selenium.Chrome;
global using OpenQA.Selenium.Support.UI;
global using ecommerceFinalProject.Utils;
global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Text;
global using System.Threading.Tasks;
global using ecommerceFinalProject.TopNav;
global using static ecommerceFinalProject.Utils.StaticHelpers;
global using ecommerceFinalProject.POMClasses;
global using System.Security.Cryptography;